name: CI
on: [push, pull_request]
jobs:
  test_postgres:
    strategy:
      matrix:
        pg: [11, 12, 13, 14, 15, 16]
        ruby: ["3.1", "3.2", "3.3"]
        gemfile: [rails_6_1, rails_7_0, rails_7_1, rails_7_2, rails_8_0]
        exclude:
          - ruby: "3.1"
            gemfile: rails_8_0
    name: PostgreSQL ${{ matrix.pg }} - Ruby ${{ matrix.ruby }} - ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v3
      - name: Start the postgres container
        run: docker compose up -d
        env:
          PGVERSION: ${{ matrix.pg }}
      - name: Setup Ruby using .ruby-version file
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
        env:
          DATABASE: postgresql
  test_sqlite:
    strategy:
      matrix:
        ruby: ["3.1", "3.2", "3.3"]
        gemfile: [rails_6_1, rails_7_0, rails_7_1, rails_7_2, rails_8_0]
        exclude:
          - ruby: "3.1"
            gemfile: rails_8_0
    name: SQLite - Ruby ${{ matrix.ruby }} - ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby using .ruby-version file
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
        env:
          DATABASE: sqlite
